from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def run(command: list[str], env: dict[str, str] | None = None) -> int:
    print("$ " + " ".join(command))
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)
    result = subprocess.run(command, cwd=ROOT, env=merged_env, check=False)
    return result.returncode


def cleanup_pycache() -> None:
    for path in ROOT.rglob("__pycache__"):
        shutil.rmtree(path, ignore_errors=True)
    for path in ROOT.rglob("*.pyc"):
        try:
            path.unlink()
        except OSError:
            pass


def validate_static_data(out_root: Path) -> int:
    path = out_root / "api" / "webdata.json"
    raw_text = path.read_text(encoding="utf-8")
    data = json.loads(raw_text)
    instruments = data.get("market", {}).get("instruments", [])
    labels = {item.get("label") for item in instruments}
    missing_price_items = [item for item in instruments if item.get("price") is None]
    dxy_items = [
        item
        for item in instruments
        if "美元" in str(item.get("label")) or item.get("sourceSymbol") in {"DXY", "DX-Y.NYB", "UUP"}
    ]
    gold_items = [
        item
        for item in instruments
        if "黄金" in str(item.get("label")) or item.get("sourceSymbol") in {"Gold", "GLD", "IAU", "GC=F"}
    ]
    checks = {
        "schemaVersion": data.get("schemaVersion") == "beidou_monitor_site_v1",
        "watchlist_nonempty": len(data.get("watchlist", [])) > 0,
        "no_public_holdings": data.get("holdings", []) == [],
        "static_export_marker": bool(data.get("status", {}).get("staticExport", {}).get("enabled")),
        "dxy_not_mislabeled": "DXY" not in labels and all(item.get("sourceNote") for item in dxy_items),
        "gold_not_mislabeled": "Gold" not in labels
        and all(item.get("sourceNote") for item in gold_items)
        and all(
            str(item.get("sourceSymbol", "")).upper() in str(item.get("label", "")).upper()
            for item in gold_items
            if str(item.get("sourceSymbol", "")).upper() in {"GLD", "IAU"}
        ),
        "missing_quotes_marked": all(
            item.get("quoteStatus") == "未取得" and item.get("displayPrice") == "未取得"
            for item in missing_price_items
        ),
        "quote_verification_status": all(item.get("verificationStatus") for item in instruments),
        "public_static_data_sanitized": all(
            token not in raw_text for token in ["C:\\", "C:/", "127.0.0.1", "localhost"]
        ),
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        print(f"Static data validation failed: {failed}")
        return 1
    print("Static data validation passed.")
    return 0


def validate_static_html(out_root: Path) -> int:
    html = (out_root / "index.html").read_text(encoding="utf-8")
    checks = {
        "generated_notice": "Generated by scripts/export_static_site.py" in html,
        "meta_description": 'name="description"' in html,
        "canonical_url": 'rel="canonical"' in html and "beidou-investment-site.pages.dev" in html,
        "open_graph_tags": 'property="og:title"' in html and 'property="og:url"' in html,
        "favicon": 'rel="icon"' in html,
        "static_data_fetch": "fetch('api/webdata.json?ts='+Date.now())" in html,
        "no_server_data_fetch": "fetch('/api/webdata?ts='+Date.now())" not in html,
        "no_server_scan_post": "await fetch('/api/scan',{method:'POST'});" not in html,
        "static_snapshot_no_refresh_button": "refreshBtn" not in html and "静态快照" in html,
        "snapshot_notice_visible": "超过 24 小时需重新导出" in html,
        "market_verification_visible": "核验状态" in html,
        "social_signal_warning_visible": "社媒线索：仅作研究提醒" in html,
        "source_health_visible": "数据源健康" in html and "renderSourceHealth(raw.sourceHealth)" in html,
        "title": "北斗投研雷达" in html,
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        print(f"Static HTML validation failed: {failed}")
        return 1
    support_files = {
        "robots": (out_root / "robots.txt").exists(),
        "sitemap": (out_root / "sitemap.xml").exists(),
        "favicon_file": (out_root / "favicon.svg").exists(),
        "builtin_files": (out_root / "builtin" / "qixing_project" / "beidou_task_status.md").exists(),
    }
    failed_support = [name for name, ok in support_files.items() if not ok]
    if failed_support:
        print(f"Static support file validation failed: {failed_support}")
        return 1
    print("Static HTML validation passed.")
    return 0


def main() -> int:
    try:
        commands = [
            [
                sys.executable,
                "-m",
                "py_compile",
                "beidou_monitor_site/preview_server.py",
                "scripts/export_static_site.py",
                "scripts/radar_dashboard.py",
                "scripts/premarket_mover_scan.py",
            ],
            [sys.executable, "-m", "unittest", "discover", "-s", "beidou_us_radar/tests", "-p", "test_*.py"],
        ]
        for command in commands:
            code = run(command)
            if code != 0:
                return code

        tmp_parent = ROOT / ".check_tmp"
        tmp_parent.mkdir(exist_ok=True)
        out_root = tmp_parent / f"static_{uuid.uuid4().hex}"
        try:
            code = run([sys.executable, "scripts/export_static_site.py"], env={"BEIDOU_STATIC_OUT_ROOT": str(out_root)})
            if code != 0:
                return code
            for validator in [validate_static_data, validate_static_html]:
                code = validator(out_root)
                if code != 0:
                    return code
        finally:
            shutil.rmtree(out_root, ignore_errors=True)
            try:
                tmp_parent.rmdir()
            except OSError:
                pass
    finally:
        cleanup_pycache()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
