from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def run(command: list[str], env: dict[str, str] | None = None) -> int:
    print("$ " + " ".join(command))
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)
    result = subprocess.run(command, cwd=ROOT, env=merged_env, check=False)
    return result.returncode


def validate_static_data(out_root: Path) -> int:
    path = out_root / "api" / "webdata.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    checks = {
        "schemaVersion": data.get("schemaVersion") == "beidou_monitor_site_v1",
        "watchlist_nonempty": len(data.get("watchlist", [])) > 0,
        "no_public_holdings": data.get("holdings", []) == [],
        "static_export_marker": bool(data.get("status", {}).get("staticExport", {}).get("enabled")),
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        print(f"Static data validation failed: {failed}")
        return 1
    print("Static data validation passed.")
    return 0


def validate_static_html(out_root: Path) -> int:
    html = (out_root / "index.html").read_text(encoding="utf-8")
    checks = {
        "generated_notice": "Generated by scripts/export_static_site.py" in html,
        "static_data_fetch": "fetch('api/webdata.json?ts='+Date.now())" in html,
        "no_server_data_fetch": "fetch('/api/webdata?ts='+Date.now())" not in html,
        "no_server_scan_post": "await fetch('/api/scan',{method:'POST'});" not in html,
        "title": "北斗投研雷达" in html,
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        print(f"Static HTML validation failed: {failed}")
        return 1
    print("Static HTML validation passed.")
    return 0


def main() -> int:
    commands = [
        [
            sys.executable,
            "-m",
            "py_compile",
            "beidou_monitor_site/preview_server.py",
            "scripts/export_static_site.py",
            "scripts/radar_dashboard.py",
            "scripts/premarket_mover_scan.py",
        ],
        [sys.executable, "-m", "unittest", "discover", "-s", "beidou_us_radar/tests", "-p", "test_*.py"],
    ]
    for command in commands:
        code = run(command)
        if code != 0:
            return code

    tmp_parent = ROOT / ".check_tmp"
    tmp_parent.mkdir(exist_ok=True)
    out_root = tmp_parent / f"static_{uuid.uuid4().hex}"
    try:
        code = run([sys.executable, "scripts/export_static_site.py"], env={"BEIDOU_STATIC_OUT_ROOT": str(out_root)})
        if code != 0:
            return code
        for validator in [validate_static_data, validate_static_html]:
            code = validator(out_root)
            if code != 0:
                return code
    finally:
        shutil.rmtree(out_root, ignore_errors=True)
        try:
            tmp_parent.rmdir()
        except OSError:
            pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
