from __future__ import annotations

import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "beidou_monitor_site"
DEFAULT_OUT_ROOT = ROOT / "docs"
DEFAULT_SOURCE_ROOT = Path(r"C:\premarket_mover_radar")
DEFAULT_PUBLIC_SITE_URL = "https://jordanwilliams5674-sys.github.io/-1"
STATIC_REFRESH_MESSAGE = "静态网站不支持在线刷新，请更新数据后重新导出。"
GENERATED_NOTICE = (
    "<!-- Generated by scripts/export_static_site.py from "
    "beidou_monitor_site/preview_dashboard.html. Do not edit this file directly. -->"
)
sys.path.insert(0, str(ROOT))

from beidou_monitor_site import preview_server  # noqa: E402


def resolve_out_root() -> Path:
    configured = os.environ.get("BEIDOU_STATIC_OUT_ROOT")
    return Path(configured) if configured else DEFAULT_OUT_ROOT


def resolve_source_root() -> Path:
    configured = os.environ.get("BEIDOU_STATIC_SOURCE_ROOT")
    candidates = [Path(configured)] if configured else []
    candidates.extend([DEFAULT_SOURCE_ROOT, ROOT])
    for candidate in candidates:
        if candidate and (candidate / "reports" / "premarket" / "latest_zh.json").exists():
            return candidate
    return ROOT


def configure_preview_source(source_root: Path) -> None:
    preview_server.ROOT = source_root
    preview_server.MARKET_STRUCTURE_FILE = source_root / "data" / "market_structure" / "latest.json"
    preview_server.RESEARCH_LOCAL_ROOT = source_root / "data" / "research_pool"


def snapshot_age_hours(data: dict) -> float | None:
    raw = data.get("market", {}).get("generatedAtUtc")
    if not raw:
        return None
    try:
        generated = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
        if generated.tzinfo is None:
            generated = generated.replace(tzinfo=timezone.utc)
        return round((datetime.now(timezone.utc) - generated.astimezone(timezone.utc)).total_seconds() / 3600, 2)
    except Exception:
        return None


def build_static_html(source_html: str) -> str:
    public_url = os.environ.get("BEIDOU_PUBLIC_SITE_URL", DEFAULT_PUBLIC_SITE_URL).rstrip("/")
    html = source_html.replace("fetch('/api/webdata?ts='+Date.now())", "fetch('api/webdata.json?ts='+Date.now())")
    html = html.replace("__PUBLIC_SITE_URL__", public_url)
    html = html.replace(
        "await fetch('/api/scan',{method:'POST'});",
        f"throw new Error('{STATIC_REFRESH_MESSAGE}');",
    )
    html = re.sub(
        r"'\s*<button class=\"tag blue\" id=\"refreshBtn\" onclick=\"refreshNow\(\)\">.*?</button>\s*'",
        "'<span class=\"tag gray\" title=\"静态网站请重新导出数据后部署\">静态快照</span>'",
        html,
        count=1,
    )
    html = re.sub(
        r"async function refreshNow\(\)\{.*?\}\n    function renderOverview",
        "async function refreshNow(){throw new Error('静态网站不支持在线刷新，请更新数据后重新导出。')}\n    function renderOverview",
        html,
        count=1,
    )
    if GENERATED_NOTICE not in html:
        html = html.replace("<!doctype html>", f"<!doctype html>\n{GENERATED_NOTICE}", 1)
    return html


def write_static_support_files(out_root: Path) -> None:
    public_url = os.environ.get("BEIDOU_PUBLIC_SITE_URL", DEFAULT_PUBLIC_SITE_URL).rstrip("/")
    (out_root / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\nSitemap: {public_url}/sitemap.xml\n",
        encoding="utf-8",
    )
    (out_root / "sitemap.xml").write_text(
        f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{public_url}/</loc>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>
""",
        encoding="utf-8",
    )
    (out_root / "favicon.svg").write_text(
        """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="12" fill="#0b0f14"/>
  <path d="M32 8l5.8 17.5H56L41.2 36.2 46.8 54 32 43 17.2 54l5.6-17.8L8 25.5h18.2L32 8z" fill="#4f8cff"/>
  <circle cx="32" cy="32" r="9" fill="#22b573"/>
</svg>
""",
        encoding="utf-8",
    )


def copy_builtin_files(out_root: Path) -> None:
    source = WEB_ROOT / "builtin_files"
    target = out_root / "builtin"
    shutil.rmtree(target, ignore_errors=True)
    if source.exists():
        shutil.copytree(source, target)


def sanitize_public_static_data(data: object, source_root: Path) -> object:
    replacements = {
        str(source_root): "local-radar-source",
        str(DEFAULT_SOURCE_ROOT): "local-radar-source",
        str(ROOT): "beidou-site-repo",
        str(WEB_ROOT): "beidou-site-builtin-files",
        "http://127.0.0.1:8766/api/live": "internal-live-api",
        "http://127.0.0.1:8766": "internal-live-api",
        "http://localhost:8766/api/live": "internal-live-api",
        "http://localhost:8766": "internal-live-api",
    }

    def clean_string(value: str) -> str:
        cleaned = value
        for old, new in replacements.items():
            cleaned = cleaned.replace(old, new)
        cleaned = re.sub(r"[A-Za-z]:\\[^\s\"']+", "local-path-redacted", cleaned)
        return cleaned

    if isinstance(data, dict):
        return {key: sanitize_public_static_data(value, source_root) for key, value in data.items()}
    if isinstance(data, list):
        return [sanitize_public_static_data(item, source_root) for item in data]
    if isinstance(data, str):
        return clean_string(data)
    return data


def validate_static_html(html: str) -> None:
    required = [
        "fetch('api/webdata.json?ts='+Date.now())",
        "api/quotes?symbols=",
        "Cloudflare Functions 只读行情",
        "静态快照",
        GENERATED_NOTICE,
    ]
    missing = [item for item in required if item not in html]
    if missing:
        raise RuntimeError(f"Static HTML export validation failed: {missing}")
    forbidden = [
        "fetch('/api/webdata?ts='+Date.now())",
        "await fetch('/api/scan',{method:'POST'});",
    ]
    present = [item for item in forbidden if item in html]
    if present:
        raise RuntimeError(f"Static HTML still contains server-only calls: {present}")


def main() -> None:
    out_root = resolve_out_root()
    out_root.mkdir(parents=True, exist_ok=True)
    shutil.rmtree(out_root / "api", ignore_errors=True)
    shutil.rmtree(out_root / "builtin", ignore_errors=True)
    for generated in [out_root / "index.html", out_root / ".nojekyll", out_root / "health.txt", out_root / "robots.txt", out_root / "sitemap.xml", out_root / "favicon.svg"]:
        if generated.exists():
            generated.unlink()
    (out_root / "api").mkdir(parents=True)

    html = build_static_html((WEB_ROOT / "preview_dashboard.html").read_text(encoding="utf-8"))
    validate_static_html(html)
    (out_root / "index.html").write_text(html, encoding="utf-8")

    source_root = resolve_source_root()
    configure_preview_source(source_root)
    data = preview_server.build_webdata()
    data.setdefault("status", {})
    age_hours = snapshot_age_hours(data)
    data["status"]["staticExport"] = {
        "enabled": True,
        "sourceRoot": "local-radar-source",
        "eventCount": len(data.get("events", [])),
        "topEventCount": len(data.get("homeV1", {}).get("topEvents", [])),
        "snapshotAgeHours": age_hours,
        "isStale": age_hours is None or age_hours > 24,
        "note": "Static snapshot for Pages deployment. Refresh the source radar data, then rerun scripts/export_static_site.py.",
    }
    data = sanitize_public_static_data(data, source_root)
    (out_root / "api" / "webdata.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    (out_root / ".nojekyll").write_text("", encoding="utf-8")
    (out_root / "health.txt").write_text("ok\n", encoding="utf-8")
    write_static_support_files(out_root)
    copy_builtin_files(out_root)


if __name__ == "__main__":
    main()

